### ISSUE TITLE
running time of iso_to_sfg

### ISSUE THREAD

**Issue by fabien-w** [r-lib/isoband#8]
Hi,
I am using the isoband fonction on a big raster to perform a raster to polygon operation. The raster is 16384*16384 pixels and contains ~ 80000 objects. Pixels with value 1 are objects and 0 is the background. the isoband function run fast ~ 100 seconds. But after that the iso_to_sfg function take about 3000 seconds to run. Do you plan to speed up this iso_to_sfg function ? it will be very usefull as you function isoband seems to be currently the fastest ways to  convert a raster to polygon in r.
Thanks !

**Comment by clauswilke** [comment]
Unfortunately I doubt there's much room for improvement. The sfg specification requires that all polygons are represented as outer rings with separate internal rings for holes. This means I need to figure out which polygon paths are inside and outside of which other polygon paths, and then separate the paths accordingly. That is a very slow operation, because every path has to be tested against every other path. By contrast, many other polygon specifications don't care and just determine what is the inside and what the outside at drawing time, using the even-odd rule or the winding rule. That's much faster, and it's for example what `grid::pathGrob()` does. Therefore we can generate isobands and draw them very rapidly with `grid::pathGrob()` yet conversion to sfg is slow.
